spring.application.name=WebGimmicks
spring.jpa.hibernate.ddl-auto=update

# set your db url and creds here
spring.datasource.url=jdbc:mysql://localhost:3306/web_gimmicks
spring.datasource.username=root
spring.datasource.password=123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
